---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "UPC Deep Learning for Artificial Intelligence 2018"
keywords:    "artificial intelligence, deep learning, teaching, course, barcelona, upc, catalonia"
description: "Course page for Deep Learning for Artificial Intelligence at UPC TelecomBCN, Barcelona, Catalonia. 2018"
source_link: "https://github.com/imatge-upc/wwwtemplate"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
# google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

